version: '3'
services:
  nginx:
   container_name: v-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
   container_name: v-mysql
   image: mysql/mysql-server:8.0.11
   environment:
    MYSQL_DATABASE: courseware
    MYSQL_ROOT_PASSWORD: wp
    MYSQL_ROOT_HOST: '%'
   - TZ=Asia/Shanghai
   ports:
   - "3306:3306"
   volumes:
   - ./mysql/data:/var/lib/mysql
   restart: always
   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app:
    restart: always
    build: ./device-service
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker